### PR TITLE
Introduce sheet importers

### PR DESCRIPTION
**Pull request by 3noch**
I split out the DB-import portion of this code (i.e. the code that actually runs the inserts into the table). That code is less than 30-lines long, so what's in this PR is by far the bulk of the work of importing. Right now parsers/validators are combined with simple function composition via `compose`. That could be confusing since function composition runs right-to-left. But I'm sure we can think of a name for a left-to-right version of it (e.g. `chain` or `pipe`?).

### CODE REVIEW

**Comment by 3noch** [comment]
Tests are passing for CPython 2.7. I'm not sure what needs to be done in order to make the others work.

**Comment by 3noch** [comment]
@guruofgentoo Made the changes we talked about and also added some more validators (`validate_min`, `validate_max`, `validate_range`). I added `chain` as a backwards alias of `compose` and added a new parser called `parse_int_or_text` for your needs.

**Comment by rsyring** [comment]
Where's the docs!?!

**Comment by 3noch** [comment]
I'm not sure what you're referring to. This new code is riddled with docs.

**Pull request merged**
